---
- platform: template
  sensors:
    nearest_phone_notify:
      unique_id: 2f4e52d5-6cc3-484e-8295-2dec8990248e
      friendly_name: Nearest phone notify service
      value_template: >
        {% if is_state("person.mike", "home") and is_state("person.wilma", "home") %}
          notify.all_phones
        {% elif is_state("person.mike", "not_home") and is_state("person.wilma", "not_home") %}
          notify.all_phones
        {% elif is_state_attr("proximity.home", "nearest", "mike-iphone") %}
          notify.mike_phone
        {% else %}
          notify.wilma_phone
        {% endif %}
