---
- platform: statistics
  unique_id: 195c8b1f-f089-494e-800b-cd1817572a0e
  name: "Attic temperature mean"
  entity_id: sensor.attic_temperature
  state_characteristic: mean
  precision: 1

- platform: statistics
  unique_id: 0ca89e2d-3e2b-447e-a213-9c8f92512f81
  name: "Attic temperature min"
  entity_id: sensor.attic_temperature
  state_characteristic: value_min
  precision: 1

- platform: statistics
  unique_id: fee3a632-e82e-4681-9481-c85f36ab3154
  name: "Attic temperature max"
  entity_id: sensor.attic_temperature
  state_characteristic: value_max
  precision: 1

- platform: statistics
  unique_id: 328fe4b4-6716-462e-ab56-9534b5c3bbb2
  name: "Bedroom temperature mean"
  entity_id: sensor.mithermometer03_temperature
  state_characteristic: mean
  precision: 1

- platform: statistics
  unique_id: ae345891-e9a8-4559-b0e0-b89880df6bfb
  name: "Bedroom temperature min"
  entity_id: sensor.mithermometer03_temperature
  state_characteristic: value_min
  precision: 1

- platform: statistics
  unique_id: 35eb2eda-290d-48ae-9eda-cea476cc1918
  name: "Bedroom temperature max"
  entity_id: sensor.mithermometer03_temperature
  state_characteristic: value_max
  precision: 1
