---
- platform: template
  sensors:
    power_consumption:
      unique_id: 8d721b11-6e19-471e-853f-f9b0135e03d5
      unit_of_measurement: W
      value_template: "{{ (states('sensor.power_consumption') | float * 1000) | round(0) }}"
    daily_energy:
      unique_id: 5b2c7256-f333-4d3d-b453-e145095d7254
      friendly_name: Daily Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.daily_energy_offpeak') | float + states('sensor.daily_energy_peak') | float) | round(3) }}"
    monthly_energy:
      unique_id: 61169b13-b4ea-4fcf-9527-90b118663367
      friendly_name: Monthly Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.monthly_energy_offpeak') | float + states('sensor.monthly_energy_peak') | float) | round(0)  }}"
    yearly_energy:
      unique_id: 4af3b666-aff0-4d07-a036-adacef4ecde0
      friendly_name: Yearly Energy
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.yearly_energy_offpeak') | float + states('sensor.yearly_energy_peak') | float) | round(0)  }}"

    daily_energy_cost:
      unique_id: cb66d666-82b4-4050-b8a9-f469fb195cf9
      friendly_name: Daily Energy Cost
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{ (states('sensor.daily_energy_peak') | float * 0.2465 + states('sensor.daily_energy_offpeak') | float * 0.2302) | round(2) }}"
    monthly_energy_cost:
      unique_id: 4a67e108-e2f9-4c6b-8c23-d3a8c8bc2c80
      friendly_name: Monthly Energy Cost
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{ (states('sensor.monthly_energy_peak') | float * 0.2465 + states('sensor.monthly_energy_offpeak') | float * 0.2302) | round(2) }}"

    daily_gas_cost:
      unique_id: 883bb809-bab2-4c16-9a9d-f7aa41a3ca30
      friendly_name: Daily Gas Cost
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{ (states('sensor.daily_gas') | float * 0.7569) | round(2) }}"
    monthly_gas_cost:
      unique_id: a7b5b306-db41-4f52-a0dc-87f66d1bbc77
      friendly_name: Monthly Gas Cost
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{ (states('sensor.monthly_gas') | float * 0.7569) | round(2) }}"

    daily_utility_cost:
      unique_id: b2b4b956-7b75-43bd-8fa2-4688d4d3deac
      friendly_name: Daily Utility Cost
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{ (states('sensor.daily_energy_peak') | float * 0.2465 + states('sensor.daily_energy_offpeak') | float * 0.2302 + states('sensor.daily_gas') | float * 0.7569) | round(2) }}"
    monthly_utility_cost:
      unique_id: 69a41d9b-87e3-4c52-a52b-28751e359972
      friendly_name: Monthly Utility Cost
      icon_template: mdi:currency-eur
      unit_of_measurement: €
      value_template: "{{ (states('sensor.monthly_energy_peak') | float * 0.2465 + states('sensor.monthly_energy_offpeak') | float * 0.2302 + states('sensor.monthly_gas') | float * 0.7569) | round(2) }}"

    daily_ac_consumption:
      unique_id: a1765b4c-394e-41b2-bb6d-62b70d4905d3
      friendly_name: Daily AC Consumption
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.living_room_ac_daily_energy') | float + states('sensor.office_ac_daily_energy') | float) | round(3) }}"
    monthly_ac_consumption:
      unique_id: ba239692-0ff1-4435-b5f1-66ebc42611aa
      friendly_name: Monthly AC Consumption
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.living_room_ac_monthly_energy') | float + states('sensor.office_ac_monthly_energy') | float) | round(0)  }}"
    yearly_ac_consumption:
      unique_id: f90b05a2-271e-4dae-bbbd-17cfc658feae
      friendly_name: Yearly AC Consumption
      unit_of_measurement: kWh
      value_template: "{{ (states('sensor.living_room_ac_yearly_energy') | float + states('sensor.office_ac_yearly_energy') | float) | round(0)  }}"
