---
- platform: template
  sensors:
    living_room_ac:
      unique_id: 1112cbf9-3f0b-4489-8737-7b9364096c9b
      friendly_name: Living Room AC currently running
      device_class: running
      value_template: >
        {{ states("sensor.living_room_ac_power") | float(0) > 25 }}
      delay_on: "00:00:30"
      delay_off: "00:00:30"
      icon_template: >
        {% if is_state("binary_sensor.living_room_ac", "on") %}
          mdi:hvac
        {% else %}
          mdi:hvac-off
        {% endif %}
