---
- platform: template
  sensors:
    no_one_home:
      unique_id: 1e5fac6d-30b9-4acb-a286-59d2b691652b
      friendly_name: No one is home
      device_class: presence
      value_template: >
        {{ not is_state("person.mike", "home")
            and not is_state("person.wilma", "home") }}
