---
- platform: template
  sensors:
    office_ac:
      unique_id: d36f9f04-9510-478d-a909-ea70aa4bfc57
      friendly_name: Office AC currently running
      device_class: running
      value_template: >
        {{ states("sensor.office_ac_power") | float(0) > 25 }}
      delay_on: "00:00:30"
      delay_off: "00:00:30"
      icon_template: >
        {% if is_state("binary_sensor.office_ac", "on") %}
          mdi:hvac
        {% else %}
          mdi:hvac-off
        {% endif %}
