---
- platform: template
  sensors:
    mike_is_driving:
      unique_id: b95a73e0-57aa-46e1-9766-0e6cbfa9021c
      friendly_name: Mike is driving
      value_template: >
        {{
          is_state("person.mike", "not_home") and
          is_state("sensor.iphone_van_mike_activity", "Automotive") or
          is_state("sensor.mike_dir_travel", "towards")
        }}
    wilma_is_driving:
      unique_id: 1892bb0f-68fe-4df8-8c01-f78d482a5bbc
      friendly_name: Wilma is driving
      value_template: >
        {{
          is_state("person.wilma", "not_home") and
          is_state("sensor.iphone_van_wilma_activity", "Automotive") or
          is_state("sensor.wilma_dir_travel", "towards")
        }}
