---
- platform: template
  sensors:
    washing_machine:
      unique_id: f511dec5-c2a5-4275-b2fe-44e4e4f4b6a2
      device_class: running
      value_template: >
        {{ states("sensor.washing_machine_power") | float(0) > 3 }}
      delay_off: "00:05:00"
      icon_template: >
        {% if is_state("binary_sensor.washing_machine", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
