---
substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ap_password: "esphome-${slug}"

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  reboot_timeout: 10min
  ap:
    ssid: "${name}"
    password: "${wifi_ap_password}"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    icon: mdi:wifi-strength-2
    update_interval: 60s
