---
id: 18866cd5-7592-41ad-9b70-658831fc1ddb
alias: Heating Boost
trigger:
  - platform: state
    entity_id: input_boolean.heating_boost
    to: "on"
action:
  - delay: 00:00:01
  - service: script.heating_boost
