---
- alias: "Shower Mode"
  description: >-
    Automatically turn off shower mode.

  id: fa15d795-5d1f-4ec8-acac-386ab73c1d27
  mode: single

  trigger:
    - platform: state
      entity_id: input_boolean.someone_showering
      to: "on"
      for:
        minutes: 30

  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.someone_showering
