- alias: "Waze ETA"
  description: >-
    Update Waze ETA when someones location has changed.

  id: f3a035ac-2f95-48d9-a562-106b251789a5
  mode: parallel
  max_exceeded: silent

  trigger:
    - platform: state
      entity_id:
        - sensor.iphone_van_mike_geocoded_location
        - sensor.iphone_van_wilma_geocoded_location
      from:

  variables:
    name: "{{ trigger.entity_id.split('.')[1].split('_')[2] }}"

  action:
    service: homeassistant.update_entity
    target:
      entity_id: sensor.eta_home_{{ name }}
