esphome:
  name: esp02
  platform: ESP8266
  board: d1_mini

# WiFi connection, correct these
# with values for your WiFi.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: esp02

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_esp02_api_password

# Enable over-the-air updates
ota:
  password: !secret esphome_esp02_ota_password

# Enable Web server
web_server:
  port: 80
    
# Text sensors with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: esphome_esp02_ip
    ssid:
      name: esphome_esp02_ssid
    bssid:
      name: esphome_esp02_bssid

sensor:
  - platform: pulse_counter
    pin: D4
    name: "Water Consumption"
    id: waterusage
    update_interval: 1s
    unit_of_measurement: 'L'
    filters:
      - multiply: 0.016666667