---
- platform: group
  unique_id: 3b0d6968-3547-494d-b6d1-e931ac055790
  name: Living Room lights
  entities:
    - light.living_room_tv_cabinet
    - light.living_room_shelf
    - light.living_room_display_cabinet
